[package]
name = "chart-js-rs"
version = "0.0.38"
edition = "2021"
authors = ["Billy Sheppard", "Luis Moreno"]
license = "Apache-2.0"
keywords = ["javascript", "dom", "wasm", "charts"]
categories = ["gui", "web-programming", "wasm"]
readme = "README.md"
description = "Chart JS API for Rust WebAssembly"
repository = "https://github.com/Billy-Sheppard/chart-js-rs"
homepage = "https://github.com/Billy-Sheppard/chart-js-rs"

[dependencies]
rust_decimal = "1.34"
serde = { version = "1.0.210", features = ["derive"] }
wasm-bindgen = { version = "0.2.90", features = ["serde-serialize"] }
gloo-utils = { version = "0.2", features = ["serde"] }
gloo-console = { version = "0.3" }
serde-wasm-bindgen = "0.6"
serde_json = "1"
thiserror = "1"
js-sys = "0.3.64"

[workspace]
members = ["examples"]

[build-dependencies]
heck = "*"
itertools = "*"
quote = "*"
proc-macro2 = "*"
syn = { features = ["parsing", "full"], version = "*" }