[package]
name = "chart-js-rs"
version = "0.0.3"
edition = "2021"
authors = ["Billy Sheppard"]
license = "Apache-2.0"
keywords = ["javascript", "dom", "wasm", "charts"]
categories = ["gui", "web-programming", "wasm"]
readme = "README.md"
description = "Chart JS API for Rust WebAssembly"
repository = "https://github.com/Billy-Sheppard/chart-js-rs"
homepage = "https://github.com/Billy-Sheppard/chart-js-rs"

[dependencies]
serde = { version = "1.0.137", features = ["derive"] }
wasm-bindgen = { version = "0.2.83" }
gloo-utils = { version = "0.1", features = ["serde"] }
serde-wasm-bindgen = "0.4"
serde_json = "1"
thiserror = "1"
js-sys = "0.3.57"

[workspace]
members = ["examples"]
