[package]
name = "chart-js-rs"
version = "0.0.1"
edition = "2021"
authors = ["Billy Sheppard"]

[dependencies]
serde = { version = "1.0.137", features = ["derive"] }
wasm-bindgen = { version = "0.2.80", features = ["serde-serialize"] }
serde_json = "1.0.81"
thiserror = "1"
js-sys = "0.3.57"