/// Generated by transpiler v0.1.0 on Fri May 27 06:16:18 UTC 2022

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct Basic {
    #[serde(rename = "definitions")]
    definitions: Definitions,
    #[serde(rename = "$id")]
    id: String,
    #[serde(rename = "$comment")]
    comment: String,
}

#[derive(Serialize, Deserialize)]
pub struct Definitions {
    #[serde(rename = "AnyObject")]
    any_object: YObject,
    #[serde(rename = "EmptyObject")]
    empty_object: YObject,
}

#[derive(Serialize, Deserialize)]
pub struct YObject {
    #[serde(rename = "title")]
    title: String,
}